.PHONY: help \
	build \
	build-linux \
	cross \
	install \
	test \
	test-race \
	e2e \
	vet \
	lint \
	fmt \
	fmt-check \
	tidy \
	tidy-check \
	verify \
	verify-linux \
	clean

.DEFAULT_GOAL := help

# Strict shell: fail on the first error, catch pipeline errors, reject unset variables.
SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c
.DELETE_ON_ERROR:
MAKEFLAGS += --no-builtin-rules

# Every Go command runs module-local: a developer go.work must never change
# what the gates build or test.
export GOWORK := off

# The binary name matches the cobra root command (`Use: "tplaiter"`).
NAME    := tplaiter
BIN     := bin/$(NAME)
PKG     := github.com/tplAIter/tplaiter

# Version compiled into the binary (overridden by release tooling: make build VERSION=vX.Y.Z).
VERSION ?= dev

# Installed-registration pins (see internal/cmd/trust_launch.go). They are empty
# by default, so `make build` yields a stock binary that refuses trust-gated
# commands with TRUST_ANCHOR_MISSING. `make install` generates an operator-pinned
# OSS registration under TRUST_ROOT and links the installed binary against it
# (docs/install.md, docs/adr/ADR-005-oss-install-registration.md). Set both pins
# explicitly to link against an existing registration instead.
REGISTRATION_PATH   ?=
REGISTRATION_SHA256 ?=

LDFLAGS := -s -w -X $(PKG)/internal/cmd.version=$(VERSION)
ifneq ($(strip $(REGISTRATION_PATH)),)
LDFLAGS += -X $(PKG)/internal/cmd.installedRegistrationPath=$(REGISTRATION_PATH)
endif
ifneq ($(strip $(REGISTRATION_SHA256)),)
LDFLAGS += -X $(PKG)/internal/cmd.installedRegistrationSHA256=$(REGISTRATION_SHA256)
endif

# Installation layout (GNU conventions; DESTDIR supports staged installs).
PREFIX  ?= /usr/local
BINDIR  ?= $(PREFIX)/bin
DESTDIR ?=

# OSS trust installation generated by `make install` (ADR-005). TRUST_ROOT must be
# an absolute path owned by the installing user; it holds the pinned trust
# documents and the trust store. TRUST_PUBLISHERS optionally names a JSON list of
# trusted template publishers. TRUST_SOURCE_PACKAGES/TRUST_PROJECT_CONTEXTS enroll
# public packages and finite contexts. TRUST_LOCAL_SOURCES is an exclusive opt-in
# for one offline operator-attested source at an absent destination. Rotation is
# unavailable for initial source enrollment.
TRUST_ROOT       ?= $(PREFIX)/lib/$(NAME)/trust
TRUST_LOCAL_SOURCES ?=
TRUST_SOURCE_PACKAGES ?=
TRUST_PROJECT_CONTEXTS ?=
TRUST_PUBLISHERS ?=
TRUST_ROTATE     ?=

# Selecting existing linker pins cannot silently discard an enrollment request.
# Parse-time refusal covers dry runs and multi-target invocations before any
# build/install recipe (or recursive make) can start.
ifneq ($(filter install,$(MAKECMDGOALS)),)
ifneq ($(strip $(REGISTRATION_PATH)$(REGISTRATION_SHA256)),)
ifneq ($(strip $(TRUST_LOCAL_SOURCES)$(TRUST_SOURCE_PACKAGES)$(TRUST_PROJECT_CONTEXTS)$(TRUST_PUBLISHERS)$(TRUST_ROTATE)),)
$(error install: REGISTRATION_PATH/REGISTRATION_SHA256 conflict with trust enrollment inputs or rotation)
endif
endif
endif

# Long-running gates share one generous per-package timeout: the trust store
# and approved-runner suites spawn real child processes and SQLite databases.
TEST_TIMEOUT ?= 30m

# Supported build targets. Windows is informational only (deferred, P21).
CROSS_TARGETS := darwin/arm64 darwin/amd64 linux/amd64 linux/arm64

# Utils ################################################################################################################

help: ## Show this menu.
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-14s\033[0m %s\n", $$1, $$2}'

# Code Quality #########################################################################################################

vet: ## Run go vet for both modules (host) and the root module for GOOS=linux.
	go vet ./...
	GOOS=linux go vet ./...
	cd tests && go vet ./...

lint: ## Run golangci-lint for both modules (each has its own .golangci.yml).
	golangci-lint run ./...
	cd tests && golangci-lint run ./...

fmt: ## Format code with gofumpt.
	gofumpt -w .

# Check git-tracked plus untracked-but-not-ignored Go files instead of walking
# the tree (`gofumpt -l .`): a Go module cache inside the worktree (for example
# .cache/go/pkg/mod) would otherwise list thousands of dependency files. CI only
# sees committed files; locally, new files are checked before they are added.
fmt-check: ## Check formatting (gofumpt) without changing files.
	@diff <(echo -n) <(git ls-files -z --cached --others --exclude-standard -- '*.go' | xargs -0 -r gofumpt -l)

tidy: ## go mod tidy for both modules.
	go mod tidy
	cd tests && go mod tidy

tidy-check: ## Fail if go.mod/go.sum of either module is not tidy.
	go mod tidy -diff
	cd tests && go mod tidy -diff

# Tests ################################################################################################################

test: ## Run unit tests (-cover).
	go test -count=1 -timeout $(TEST_TIMEOUT) -cover ./...

test-race: ## Run unit tests with the race detector.
	go test -race -count=1 -timeout $(TEST_TIMEOUT) ./...

e2e: ## Run the e2e harness (tests/, a separate black-box module over the binary).
	cd tests && go test -count=1 -timeout $(TEST_TIMEOUT) ./...

# Build ################################################################################################################

build: ## Build the tplaiter binary in bin/.
	@mkdir -p bin
	CGO_ENABLED=0 go build -trimpath -ldflags="$(LDFLAGS)" -o $(BIN) .
	@echo "built $(BIN) (version=$(VERSION))"

build-linux: ## Compile every package for GOOS=linux (amd64 and arm64).
	GOOS=linux GOARCH=amd64 go build ./...
	GOOS=linux GOARCH=arm64 go build ./...

cross: ## Compile every package for all supported targets (windows is informational).
	@for target in $(CROSS_TARGETS); do \
		echo "go build ./... ($$target)"; \
		GOOS=$${target%/*} GOARCH=$${target#*/} go build ./...; \
	done
	@echo "go build ./... (windows/amd64, informational)"
	-GOOS=windows GOARCH=amd64 go build ./... || echo "windows/amd64: not supported yet (deferred)"

install: ## Generate the OSS trust registration, link against it, and install into $(DESTDIR)$(BINDIR).
	@if [ -n "$(TRUST_LOCAL_SOURCES)" ] && { [ -n "$(TRUST_PUBLISHERS)$(TRUST_SOURCE_PACKAGES)" ] || [ -n "$(filter 1 yes true,$(TRUST_ROTATE))" ] || [ -z "$(TRUST_PROJECT_CONTEXTS)" ]; }; then echo "install: TRUST_LOCAL_SOURCES requires TRUST_PROJECT_CONTEXTS and forbids external publishers/packages and rotation" >&2; exit 1; fi
	@mkdir -p "$(dir $(BIN))"
ifeq ($(strip $(REGISTRATION_PATH)$(REGISTRATION_SHA256)),)
	@if [ -n "$(DESTDIR)" ]; then echo "install: DESTDIR staging cannot generate an operator-pinned registration; set REGISTRATION_PATH and REGISTRATION_SHA256" >&2; exit 1; fi
	go run ./cmd/tplaiter-oss-register --root "$(TRUST_ROOT)" --output "$(dir $(BIN))registration.pins" \
		$(if $(TRUST_PUBLISHERS),--publishers "$(TRUST_PUBLISHERS)") \
		$(if $(TRUST_LOCAL_SOURCES),--local-sources "$(TRUST_LOCAL_SOURCES)") \
		$(if $(TRUST_SOURCE_PACKAGES),--source-packages "$(TRUST_SOURCE_PACKAGES)") \
		$(if $(TRUST_PROJECT_CONTEXTS),--project-contexts "$(TRUST_PROJECT_CONTEXTS)") $(if $(filter 1 yes true,$(TRUST_ROTATE)),--rotate)
	$(MAKE) --no-print-directory build $$(cat "$(dir $(BIN))registration.pins")
else
	@if [ -z "$(REGISTRATION_PATH)" ] || [ -z "$(REGISTRATION_SHA256)" ]; then echo "install: set both REGISTRATION_PATH and REGISTRATION_SHA256, or neither" >&2; exit 1; fi
	$(MAKE) --no-print-directory build
endif
	install -d "$(DESTDIR)$(BINDIR)"
	install -m 0755 $(BIN) "$(DESTDIR)$(BINDIR)/$(NAME)"
	@echo "installed $(DESTDIR)$(BINDIR)/$(NAME)"
	@echo "next: run '$(DESTDIR)$(BINDIR)/$(NAME) trust provision' once to enroll the trust store"

clean: ## Remove build artifacts.
	rm -rf bin dist

# Aggregate gates ######################################################################################################

verify: build build-linux vet fmt-check tidy-check test-race e2e lint ## Run every canonical gate (host).

# verify-linux runs inside a plain golang image with a read-only module cache
# mounted (no gofumpt or golangci-lint there; those run on the host). VCS
# stamping is disabled because a linked worktree's .git points outside the
# mounted directory.
verify-linux: export GOFLAGS += -buildvcs=false
verify-linux: ## Linux gate for Docker (build, vet, test-race, e2e; no lint/fmt).
	go build ./...
	go vet ./...
	cd tests && go vet ./...
	go test -race -count=1 -timeout $(TEST_TIMEOUT) ./...
	cd tests && go test -count=1 -timeout $(TEST_TIMEOUT) ./...
