package cmd

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io/fs"
	"os"
	"strings"
	"time"

	"github.com/tplAIter/tplaiter/internal/bootstrap"
	"github.com/tplAIter/tplaiter/internal/ossinstall"
	"github.com/tplAIter/tplaiter/internal/trustload"
)

// These are installation-time linker pins. Empty values deliberately leave
// stock trust-dependent commands unavailable; flags and environment never
// participate in selecting them. `make install` sets both from the
// operator-pinned OSS registration generated by cmd/tplaiter-oss-register
// (docs/adr/ADR-005-oss-install-registration.md).
var (
	installedRegistrationPath   string
	installedRegistrationSHA256 string
)

// ErrNotProvisioned reports a valid installed registration whose trust store
// has not been enrolled yet. `tplaiter trust provision` enrolls it from the
// pinned initial state and bundle only.
var ErrNotProvisioned = errors.New("TRUST_NOT_PROVISIONED: run 'tplaiter trust provision' once after installation")

func installedInvocation(ctx context.Context) (invocation, error) {
	if installedRegistrationPath == "" || installedRegistrationSHA256 == "" {
		return invocation{}, trustload.ErrAnchorMissing
	}
	raw, err := readFixedTrustDocument(ctx, installedRegistrationPath)
	if err != nil {
		return invocation{}, trustload.ErrAnchorMissing
	}
	if !rawDigestMatches(raw, installedRegistrationSHA256) {
		return invocation{}, trustload.ErrPinMismatch
	}
	r, err := ossinstall.DecodeRegistration(raw)
	if err != nil {
		return invocation{}, trustload.ErrConfigInvalid
	}
	in := invocation{Selection: r.Selection(), ProjectKey: r.ProjectKey, Clock: bootstrap.ClockFunc(time.Now)}
	if err := in.Selection.Validate(); err != nil || in.ProjectKey == "" {
		return invocation{}, trustload.ErrConfigInvalid
	}
	return in, nil
}

// storeProvisioned reports whether the OSS trust store selected by in has
// been created. It returns ErrNotProvisioned only when the installation
// itself loads and the store path is absent; every other failure is left to
// the regular runtime composition, which reports its own typed error.
func storeProvisioned(ctx context.Context, in invocation) error {
	loaded, loadErr := trustload.Load(ctx, in.Selection)
	if loadErr == nil && loaded.Install.OSS != nil {
		if _, statErr := os.Lstat(loaded.Install.OSS.StorePath); errors.Is(statErr, fs.ErrNotExist) {
			return ErrNotProvisioned
		}
	}
	return nil
}

// requireProvisioned resolves the command invocation and fails with
// ErrNotProvisioned before runtime composition when the store is missing.
func requireProvisioned(ctx context.Context) error {
	in, err := commandInvocation(ctx)
	if err != nil {
		return err
	}
	return storeProvisioned(ctx, in)
}

func rawDigestMatches(raw []byte, want string) bool {
	if !strings.HasPrefix(want, "sha256:") || len(want) != len("sha256:")+64 {
		return false
	}
	if _, err := hex.DecodeString(strings.TrimPrefix(want, "sha256:")); err != nil {
		return false
	}
	h := sha256.Sum256(raw)
	return want == "sha256:"+hex.EncodeToString(h[:])
}
